using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using UnityEditor;
using UnityEditor.Build;
using UnityEditor.Compilation;
using UnityEngine;

namespace BrainRegion.RuntimeBridge.Editor
{
    /// <summary>
    /// Generates direct-access IRpcPropertyAdapter MonoBehaviours from explicit
    /// attributes. Reflection is confined to the Editor; emitted Player code uses
    /// ordinary typed field/property access and shared bounded value validators.
    /// </summary>
    public static class RuntimePropertyBindingGenerator
    {
        public const string DefaultOutputDirectory = "Assets/BrainRegionGenerated";
        private const string GeneratedSuffix = "BrainRegionRpcAdapter.cs";

        [MenuItem("Tools/BrainRegion/Generate Runtime Property Bindings")]
        public static void GenerateAllMenu()
        {
            IReadOnlyList<string> paths = GenerateAll(DefaultOutputDirectory);
            Debug.Log($"[BrainRegion] Generated {paths.Count} Runtime Scene RPC binding adapter(s)");
        }

        public static void GenerateAllBatch()
        {
            GenerateAllMenu();
        }

        public static IReadOnlyList<string> GenerateAll(string outputDirectory)
        {
            ValidateOutputDirectory(outputDirectory);
            string absoluteOutput = Path.GetFullPath(outputDirectory);
            Directory.CreateDirectory(absoluteOutput);

            var expected = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            var generated = new List<string>();
            var playerAssemblies = new HashSet<string>(
                CompilationPipeline.GetAssemblies(AssembliesType.Player)
                    .Select(assembly => assembly.name),
                StringComparer.Ordinal);
            foreach (Type type in TypeCache.GetTypesWithAttribute<RpcBindingTargetAttribute>()
                         .Where(candidate => playerAssemblies.Contains(
                             candidate.Assembly.GetName().Name))
                         .OrderBy(candidate => candidate.FullName, StringComparer.Ordinal))
            {
                string className = GetGeneratedClassName(type);
                string assetPath = outputDirectory.TrimEnd('/') + "/" + className + ".cs";
                string absolutePath = Path.GetFullPath(assetPath);
                string source = GenerateSource(type);
                expected.Add(absolutePath);
                generated.Add(assetPath);
                if (!File.Exists(absolutePath) ||
                    !string.Equals(File.ReadAllText(absolutePath), source, StringComparison.Ordinal))
                    File.WriteAllText(absolutePath, source, new UTF8Encoding(false));
            }

            foreach (string stalePath in Directory.GetFiles(
                         absoluteOutput,
                         "*" + GeneratedSuffix,
                         SearchOption.TopDirectoryOnly))
            {
                if (!expected.Contains(Path.GetFullPath(stalePath)))
                {
                    string staleAssetPath = outputDirectory.TrimEnd('/') + "/" +
                        Path.GetFileName(stalePath);
                    AssetDatabase.DeleteAsset(staleAssetPath);
                }
            }
            AssetDatabase.Refresh(ImportAssetOptions.ForceSynchronousImport);
            return generated;
        }

        public static string GenerateSource(Type targetType)
        {
            BindingTarget target = InspectTarget(targetType);
            string targetTypeName = "global::" + targetType.FullName.Replace('+', '.');
            string className = GetGeneratedClassName(targetType);
            var source = new StringBuilder();
            source.AppendLine("// <auto-generated />")
                .AppendLine("using System;")
                .AppendLine("using System.Collections.Generic;")
                .AppendLine("using BrainRegion.RuntimeBridge;")
                .AppendLine("using Newtonsoft.Json.Linq;")
                .AppendLine("using UnityEngine;")
                .AppendLine()
                .AppendLine("namespace BrainRegion.RuntimeBridge.Generated")
                .AppendLine("{")
                .AppendLine("    [DisallowMultipleComponent]")
                .Append("    [RequireComponent(typeof(").Append(targetTypeName).AppendLine("))]")
                .Append("    public sealed class ").Append(className)
                .AppendLine(" : MonoBehaviour, IRpcPropertyAdapter")
                .AppendLine("    {")
                .Append("        [SerializeField] private ").Append(targetTypeName)
                .AppendLine(" target;")
                .AppendLine()
                .AppendLine("        private static readonly IReadOnlyList<RpcPropertyDescriptor> Properties =")
                .AppendLine("            new[]")
                .AppendLine("            {");
            foreach (BindingMember member in target.Members)
                AppendDescriptor(source, member);
            source.AppendLine("            };")
                .AppendLine()
                .Append("        public string ComponentKey => \"")
                .Append(Escape(target.Attribute.ComponentKey)).AppendLine("\";")
                .Append("        public string TypeId => \"")
                .Append(Escape(target.Attribute.TypeId)).AppendLine("\";")
                .AppendLine()
                .AppendLine("        public IReadOnlyList<RpcPropertyDescriptor> DescribeProperties() => Properties;")
                .AppendLine()
                .AppendLine("        public bool TryRead(string propertyId, out JToken value, out string error)")
                .AppendLine("        {")
                .AppendLine("            if (!TryGetTarget(out error))")
                .AppendLine("            {")
                .AppendLine("                value = null;")
                .AppendLine("                return false;")
                .AppendLine("            }")
                .AppendLine("            switch (propertyId)")
                .AppendLine("            {");
            foreach (BindingMember member in target.Members)
            {
                source.Append("                case \"").Append(Escape(member.Attribute.PropertyId))
                    .AppendLine("\":")
                    .Append("                    value = new JValue(target.@")
                    .Append(member.Member.Name).AppendLine(");")
                    .AppendLine("                    error = null;")
                    .AppendLine("                    return true;");
            }
            source.AppendLine("                default:")
                .AppendLine("                    value = null;")
                .AppendLine("                    error = \"Unknown generated property\";")
                .AppendLine("                    return false;")
                .AppendLine("            }")
                .AppendLine("        }")
                .AppendLine()
                .AppendLine("        public bool TryValidate(")
                .AppendLine("            string propertyId,")
                .AppendLine("            JToken proposed,")
                .AppendLine("            out JToken canonical,")
                .AppendLine("            out string error)")
                .AppendLine("        {")
                .AppendLine("            switch (propertyId)")
                .AppendLine("            {");
            foreach (BindingMember member in target.Members)
                AppendValidationCase(source, member);
            source.AppendLine("                default:")
                .AppendLine("                    canonical = null;")
                .AppendLine("                    error = \"Unknown generated property\";")
                .AppendLine("                    return false;")
                .AppendLine("            }")
                .AppendLine("        }")
                .AppendLine()
                .AppendLine("        public bool TryWrite(string propertyId, JToken canonical, out string error)")
                .AppendLine("        {")
                .AppendLine("            if (!TryGetTarget(out error) ||")
                .AppendLine("                !TryValidate(propertyId, canonical, out JToken normalized, out error))")
                .AppendLine("                return false;")
                .AppendLine("            switch (propertyId)")
                .AppendLine("            {");
            foreach (BindingMember member in target.Members)
            {
                source.Append("                case \"").Append(Escape(member.Attribute.PropertyId))
                    .AppendLine("\":")
                    .Append("                    target.@").Append(member.Member.Name)
                    .Append(" = normalized.Value<").Append(GetSourceTypeName(member.ValueType))
                    .AppendLine(">();")
                    .AppendLine("                    error = null;")
                    .AppendLine("                    return true;");
            }
            source.AppendLine("                default:")
                .AppendLine("                    error = \"Unknown generated property\";")
                .AppendLine("                    return false;")
                .AppendLine("            }")
                .AppendLine("        }")
                .AppendLine()
                .AppendLine("        private bool TryGetTarget(out string error)")
                .AppendLine("        {")
                .AppendLine("            if (target == null) target = GetComponent<" + targetTypeName + ">();")
                .AppendLine("            error = target == null ? \"Generated binding target is missing\" : null;")
                .AppendLine("            return target != null;")
                .AppendLine("        }")
                .AppendLine("    }")
                .AppendLine("}");
            return source.ToString().Replace("\r\n", "\n");
        }

        public static string GetGeneratedClassName(Type targetType)
        {
            if (targetType == null || string.IsNullOrEmpty(targetType.FullName))
                throw new ArgumentException("Binding target type must have a full name", nameof(targetType));
            var name = new StringBuilder();
            foreach (char character in targetType.FullName)
                name.Append(char.IsLetterOrDigit(character) ? character : '_');
            name.Append(GeneratedSuffix.Substring(0, GeneratedSuffix.Length - 3));
            return name.ToString();
        }

        private static BindingTarget InspectTarget(Type type)
        {
            if (type == null || type.IsAbstract || type.IsGenericType ||
                !typeof(MonoBehaviour).IsAssignableFrom(type) ||
                !(type.IsPublic || type.IsNestedPublic))
                throw new BuildFailedException("RpcBindingTarget must be a public non-generic MonoBehaviour");
            var target = (RpcBindingTargetAttribute)Attribute.GetCustomAttribute(
                type,
                typeof(RpcBindingTargetAttribute),
                false);
            if (target == null || !SceneProtocol.IsIdentifier(target.ComponentKey, 128) ||
                target.ComponentKey.Contains("/") || !SceneProtocol.IsIdentifier(target.TypeId, 128))
                throw new BuildFailedException($"Generated binding target '{type.FullName}' has invalid identifiers");

            List<BindingMember> members = type
                .GetMembers(BindingFlags.Instance | BindingFlags.Public)
                .Select(member => BuildMember(member))
                .Where(member => member != null)
                .OrderBy(member => member.Attribute.PropertyId, StringComparer.Ordinal)
                .ToList();
            if (members.Count == 0)
                throw new BuildFailedException($"Generated binding target '{type.FullName}' exposes no properties");
            if (members.Select(member => member.Attribute.PropertyId)
                .Distinct(StringComparer.Ordinal).Count() != members.Count)
                throw new BuildFailedException($"Generated binding target '{type.FullName}' has duplicate property IDs");
            return new BindingTarget { Attribute = target, Members = members };
        }

        private static BindingMember BuildMember(MemberInfo member)
        {
            var attribute = (RpcExposedPropertyAttribute)Attribute.GetCustomAttribute(
                member,
                typeof(RpcExposedPropertyAttribute),
                true);
            if (attribute == null) return null;

            Type valueType;
            if (member is FieldInfo field)
            {
                if (field.IsInitOnly || field.IsLiteral)
                    throw new BuildFailedException($"Generated binding field '{member.Name}' must be writable");
                valueType = field.FieldType;
            }
            else if (member is PropertyInfo property)
            {
                if (property.GetIndexParameters().Length != 0 || property.GetGetMethod() == null ||
                    property.GetSetMethod() == null)
                    throw new BuildFailedException($"Generated binding property '{member.Name}' must have public get/set accessors");
                valueType = property.PropertyType;
            }
            else
            {
                throw new BuildFailedException("RpcExposedProperty can only annotate fields or properties");
            }

            if (valueType != typeof(bool) && valueType != typeof(int) &&
                valueType != typeof(float) && valueType != typeof(double) &&
                valueType != typeof(string))
                throw new BuildFailedException($"Generated binding member '{member.Name}' uses unsupported type '{valueType}'");
            if (!IsPropertyIdentifier(attribute.PropertyId))
                throw new BuildFailedException($"Generated binding member '{member.Name}' has an invalid property ID");
            if (attribute.DisplayName != null && attribute.DisplayName.Length > 256)
                throw new BuildFailedException($"Generated binding member '{member.Name}' display name is too long");
            bool numeric = valueType == typeof(int) || valueType == typeof(float) ||
                valueType == typeof(double);
            if (!numeric &&
                (!double.IsNaN(attribute.Minimum) || !double.IsNaN(attribute.Maximum)))
                throw new BuildFailedException($"Generated binding member '{member.Name}' uses numeric bounds on a non-numeric type");
            if (!double.IsNaN(attribute.Minimum) && double.IsInfinity(attribute.Minimum) ||
                !double.IsNaN(attribute.Maximum) && double.IsInfinity(attribute.Maximum) ||
                !double.IsNaN(attribute.Minimum) && !double.IsNaN(attribute.Maximum) &&
                attribute.Minimum > attribute.Maximum)
                throw new BuildFailedException($"Generated binding member '{member.Name}' has invalid numeric bounds");
            if (valueType == typeof(string) &&
                (attribute.MaximumLength < 1 || attribute.MaximumLength > 16384))
                throw new BuildFailedException($"Generated binding member '{member.Name}' has an invalid string limit");
            return new BindingMember { Member = member, ValueType = valueType, Attribute = attribute };
        }

        private static void AppendDescriptor(StringBuilder source, BindingMember member)
        {
            source.AppendLine("                new RpcPropertyDescriptor")
                .AppendLine("                {")
                .Append("                    PropertyId = \"").Append(Escape(member.Attribute.PropertyId))
                .AppendLine("\",")
                .Append("                    DisplayName = \"")
                .Append(Escape(member.Attribute.DisplayName ?? member.Member.Name)).AppendLine("\",")
                .Append("                    ValueType = \"").Append(GetWireType(member.ValueType)).AppendLine("\",")
                .AppendLine("                    ReadOnly = false,")
                .Append("                    Persistent = ").Append(member.Attribute.Persistent ? "true" : "false")
                .AppendLine(",");
            if (!double.IsNaN(member.Attribute.Minimum))
                source.Append("                    Minimum = ").Append(FormatDouble(member.Attribute.Minimum)).AppendLine(",");
            if (!double.IsNaN(member.Attribute.Maximum))
                source.Append("                    Maximum = ").Append(FormatDouble(member.Attribute.Maximum)).AppendLine(",");
            source.AppendLine("                },");
        }

        private static void AppendValidationCase(StringBuilder source, BindingMember member)
        {
            string minimum = double.IsNaN(member.Attribute.Minimum)
                ? "null"
                : FormatDouble(member.Attribute.Minimum);
            string maximum = double.IsNaN(member.Attribute.Maximum)
                ? "null"
                : FormatDouble(member.Attribute.Maximum);
            source.Append("                case \"").Append(Escape(member.Attribute.PropertyId)).AppendLine("\":");
            if (member.ValueType == typeof(bool))
                source.AppendLine("                    return RpcGeneratedBindingValues.TryBoolean(proposed, out canonical, out error);");
            else if (member.ValueType == typeof(int))
                source.Append("                    return RpcGeneratedBindingValues.TryInteger(proposed, ")
                    .Append(minimum).Append(", ").Append(maximum)
                    .AppendLine(", out canonical, out error);");
            else if (member.ValueType == typeof(float) || member.ValueType == typeof(double))
                source.Append("                    return RpcGeneratedBindingValues.TryNumber(proposed, ")
                    .Append(minimum).Append(", ").Append(maximum).Append(", ")
                    .Append(member.ValueType == typeof(float) ? "true" : "false")
                    .AppendLine(", out canonical, out error);");
            else
                source.Append("                    return RpcGeneratedBindingValues.TryString(proposed, ")
                    .Append(member.Attribute.MaximumLength)
                    .AppendLine(", out canonical, out error);");
        }

        private static string GetWireType(Type type)
        {
            if (type == typeof(bool)) return "boolean";
            if (type == typeof(int)) return "integer";
            if (type == typeof(string)) return "string";
            return "number";
        }

        private static string GetSourceTypeName(Type type)
        {
            if (type == typeof(bool)) return "bool";
            if (type == typeof(int)) return "int";
            if (type == typeof(float)) return "float";
            if (type == typeof(double)) return "double";
            return "string";
        }

        private static string FormatDouble(double value)
        {
            return value.ToString("R", CultureInfo.InvariantCulture) + "D";
        }

        private static string Escape(string value)
        {
            if (value == null) return string.Empty;
            return value.Replace("\\", "\\\\").Replace("\"", "\\\"")
                .Replace("\r", "\\r").Replace("\n", "\\n");
        }

        private static bool IsPropertyIdentifier(string value)
        {
            return !string.IsNullOrEmpty(value) && value.Length <= 128 &&
                value.All(character => char.IsLetterOrDigit(character) ||
                    character == '.' || character == '_' || character == '-');
        }

        private static void ValidateOutputDirectory(string outputDirectory)
        {
            if (string.IsNullOrWhiteSpace(outputDirectory) ||
                !outputDirectory.StartsWith("Assets/", StringComparison.Ordinal) ||
                outputDirectory.Contains(".."))
                throw new ArgumentException("Generated binding output must be below Assets", nameof(outputDirectory));
        }

        private sealed class BindingTarget
        {
            public RpcBindingTargetAttribute Attribute;
            public List<BindingMember> Members;
        }

        private sealed class BindingMember
        {
            public MemberInfo Member;
            public Type ValueType;
            public RpcExposedPropertyAttribute Attribute;
        }
    }
}
