// <auto-generated />
using System;
using System.Collections.Generic;
using BrainRegion.RuntimeBridge;
using Newtonsoft.Json.Linq;
using UnityEngine;

namespace BrainRegion.RuntimeBridge.Generated
{
    [DisallowMultipleComponent]
    [RequireComponent(typeof(global::BrainRegion.ScenePipeSmoke.GeneratedSmokeProperties))]
    public sealed class BrainRegion_ScenePipeSmoke_GeneratedSmokePropertiesBrainRegionRpcAdapter : MonoBehaviour, IRpcPropertyAdapter
    {
        [SerializeField] private global::BrainRegion.ScenePipeSmoke.GeneratedSmokeProperties target;

        private static readonly IReadOnlyList<RpcPropertyDescriptor> Properties =
            new[]
            {
                new RpcPropertyDescriptor
                {
                    PropertyId = "brightness",
                    DisplayName = "Generated Brightness",
                    ValueType = "integer",
                    ReadOnly = false,
                    Persistent = true,
                    Minimum = 0D,
                    Maximum = 10D,
                },
            };

        public string ComponentKey => "generated";
        public string TypeId => "brainregion.smoke.generated";

        public IReadOnlyList<RpcPropertyDescriptor> DescribeProperties() => Properties;

        public bool TryRead(string propertyId, out JToken value, out string error)
        {
            if (!TryGetTarget(out error))
            {
                value = null;
                return false;
            }
            switch (propertyId)
            {
                case "brightness":
                    value = new JValue(target.@Brightness);
                    error = null;
                    return true;
                default:
                    value = null;
                    error = "Unknown generated property";
                    return false;
            }
        }

        public bool TryValidate(
            string propertyId,
            JToken proposed,
            out JToken canonical,
            out string error)
        {
            switch (propertyId)
            {
                case "brightness":
                    return RpcGeneratedBindingValues.TryInteger(proposed, 0D, 10D, out canonical, out error);
                default:
                    canonical = null;
                    error = "Unknown generated property";
                    return false;
            }
        }

        public bool TryWrite(string propertyId, JToken canonical, out string error)
        {
            if (!TryGetTarget(out error) ||
                !TryValidate(propertyId, canonical, out JToken normalized, out error))
                return false;
            switch (propertyId)
            {
                case "brightness":
                    target.@Brightness = normalized.Value<int>();
                    error = null;
                    return true;
                default:
                    error = "Unknown generated property";
                    return false;
            }
        }

        private bool TryGetTarget(out string error)
        {
            if (target == null) target = GetComponent<global::BrainRegion.ScenePipeSmoke.GeneratedSmokeProperties>();
            error = target == null ? "Generated binding target is missing" : null;
            return target != null;
        }
    }
}
